### ISSUE TITLE
Server went down during SAIN school dry run on Dec. 22, 2021

### ISSUE THREAD

**Issue by jgarci40** [SAIN-Project/Frontend#40]
We need to determine why this happened so it doesn't happen during the real school session.

**Comment by khoiminhpham** [comment]
This was not server down. 
It was because of me, my RIT account was deactivated a day before that. So on that day I had to use Ibrahim's account to remote access and run my back-end auto-start bash. That caused unauthorized activity whenever back-end service tried to make any changes to the machine.
The issue was solved the day after.
